Testing changes to gather dashboard admin logs

diff --git a/must-gather/collection-scripts/gather b/must-gather/collection-scripts/gather
--- a/must-gather/collection-scripts/gather
+++ b/must-gather/collection-scripts/gather
@@ -1,18 +1,21 @@
 #!/bin/bash
 
-kfdefs=$(oc get kfdefs --all-namespaces -o=jsonpath='{range .items[*]}{.metadata.namespace}{"\n"}{end}')
+dashboard_pods=$(oc get pods -l app=odh-dashboard --all-namespaces=true -o=jsonpath='{range .items[*].metadata}{.name}{"\n"}{end}')
 
+# Prepare folder for logs
+mkdir -p must-gather/odh-dashboard || echo "Error creating odh-dashboard directory"
+echo $dashboard_pods
 # Get logs from all KfDef namespaces
-for i in $kfdefs;
+for i in $dashboard_pods;
 do
-# Get pod logs for all the pods in KfDef namespaces
-oc adm inspect namespace/"$i" --dest-dir=must-gather || echo "Error getting logs from $i"
+# Get pod logs for all the pods
+mkdir must-gather/odh-dashboard/$i || echo "Error creating odh-dashboard directory"
+oc rsync $i:/opt/app-root/src/logs/adminActivity.log must-gather/odh-dashboard/$i/|| echo "Error getting logs from $i"
 
 done
 
 ## Get Operator pod logs
-mkdir must-gather/odh-operator || echo "Error creating odh-operator directory"
-oc logs deployment/opendatahub-operator -n openshift-operators >> must-gather/odh-operator/pod.log
+# oc logs deployment/opendatahub-operator -n openshift-operators >> must-gather/odh-operator/pod.log
 
 exit 0
 
